# Generated by Django 4.0.4 on 2022-05-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('unit_tutoring', models.CharField(max_length=200)),
                ('level_education', models.CharField(max_length=200)),
            ],
        ),
    ]
