# Generated by Django 4.0.3 on 2022-04-17 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('offering_id', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=16)),
                ('date_filled', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=16)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('instructor_email', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=16)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('num_of_students', models.IntegerField(blank=True, default=0, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
                ('instructor_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.instructor')),
                ('offering_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.attendance')),
            ],
        ),
    ]
