# Generated by Django 4.0.4 on 2022-04-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_attendance_course_instructor_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='password',
            field=models.CharField(default=1234, max_length=16),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1234, max_length=16),
        ),
    ]
