# Generated by Django 4.0.4 on 2022-04-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_instructor_password_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='instructor_email',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='offering_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Offering',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
