# Generated by Django 4.0.4 on 2022-05-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('vision', models.CharField(blank=True, max_length=2000, null=True)),
                ('mission', models.CharField(blank=True, max_length=2000, null=True)),
                ('values', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
