# Generated by Django 3.2.5 on 2022-05-28 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_exam_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('course', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='students.course')),
                ('fee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='students.fee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('location_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('profile', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.profile')),
            ],
        ),
    ]
